export const keys = {
  category: "category",
  category_detail: "category_detail",
  number_of_shots: "number_of_shots",
  data_type: "data_type",
  month: "month",
  day: "day",
  time: "time",
  prefecture: "prefecture",
  address: "address",
  phone: "phone",
  email: "email",
  request: "request",
  sum: "sum",
};
