export const keys = {
  address: "address",
  category: "category",
  category_detail: "category_detail",
  data_type: "data_type",
  day: "day",
  email: "email",
  month: "month",
  number_of_shots: "number_of_shots",
  phone: "phone",
  prefecture: "prefecture",
  request: "request",
  time: "time",
  sum: "sum",
};
