import React, { useState, useEffect } from "react";
import { Box, MotionTextarea } from "../../styles/components";
import { PageTransition } from "../../components/PageTransition";
import { Nav } from "../../components/reservation";
import { loadYamls } from "../../lib/posts";

import Head from "next/head";
import { insertBreak } from "../../lib/convert";
import { Success } from "../../public/img/svg";

export const getStaticProps = async () => {
  const postDatas = await loadYamls([
    "reservation/common.yml",
    "reservation/step5.yml",
  ]);
  return {
    props: {
      data: postDatas,
    },
  };
};

export default function Step5({ data }) {
  return (
    <PageTransition>
      <Head>
        <title>
          Shotfelice-ご予約-{data.nav[3].slice(3, data.nav[3].length)}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        display="flex"
        justifyContent="center"
        alignItems="center"
        flexDirection="column"
        pt={[20, 50]}
      >
        <Box maxWidth={960} width="100%" overflow="hidden" px={["4%", 20]}>
          {/* ---- Step Header ---- */}
          <Nav nav={data.nav} />
          <Box my={[20, 50]} width="100%" borderBottom="solid 1px #e1e1e1" />
          {/* ---- Step title ---- */}
          <Box fontSize={34} fontWeight="bold" mb={27}>
            {data.success_msg.title}
          </Box>
          <Box
            backgroundColor="green"
            width="100%"
            color="white"
            fontSize={18}
            py={19}
            px={30}
            display="flex"
            alignItems="center"
            mb={80}
          >
            <Box mr={10}>
              <Success />
            </Box>
            {data.success_msg.body}
          </Box>

          <Box fontSize={20} lineHeight={2} mb={200}>
            {insertBreak(data.success_msg.foot)}
          </Box>
        </Box>
      </Box>
    </PageTransition>
  );
}
