import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React, { useState } from 'react';

import { PageTransition } from '../components/PageTransition';
import { Box, MotionDiv, Clickable, Text } from '../styles/components';

import { getPostData } from '../lib/posts';
import HamburgerMenu from '../components/HamburgerMenu';
import { Button } from '../components/Button';

import OutsideClickHandler from 'react-outside-click-handler';


export const getStaticProps = async () => {
  const postData = await getPostData("home");
  return {
    props: {
      data: postData,
    }
  }
}

export default function Home({ data }) {
  // ホームディレクトリのみpadding-top : 0;
  if (typeof document !== 'undefined') {
    document.getElementsByTagName("body")[0].style.paddingTop = 0;
  }

  return (
    <PageTransition width="100%" height="100%" styles={{ overflow: "hidden" }}>
      <Head>
        <title>Shotfelice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Background Image */}
      <Box width="100vw" height="100%" position="absolute" overflow="hidden" zIndex="-1">
        <Image
          src="/img/general/background_image-min.jpg"
          alt="background_image"
          layout="fill"
          objectFit="cover"
          quality={100}
        >
        </Image>
      </Box>

      <TopBar top_bar={data.top_bar} />
      <NavBar nav={data.nav} />
      <Subheading subheading={data.subheading} nav={data.nav} />
      <Box height={"100%"} background="red"></Box>

    </PageTransition>
  )
}

function NavBar({ nav }) {
  const [isOpen, setIsOpen] = useState(false);
  const variants = {
    false: {
      opacity: 0,
      height: 0
    },
    true: {
      opacity: 1,
      height: 300
    }
  }

  return (
    <Box position="relative" height={[40, 90]}>
      <OutsideClickHandler onOutsideClick={() => {
        if (isOpen) {
          setIsOpen(false);
        }
      }}>
        <HamburgerMenu
          position="absolute"
          right="5%"
          top={30}
          isOpen={isOpen}
          onClick={() => { setIsOpen(!isOpen); }}
          display={["block", "none"]}
          zIndex={2}
        />
        <MotionDiv
          position="absolute"
          px={["5%", 80]}
          py={[40, 0]}
          width="100%"
          display="flex"
          flexDirection={["column", "row"]}
          alignItems={["flex-start", "center"]} justifyContent="flex-start"
          mt={[0, 30]}
          background={["white", "none"]}
          variants={variants}
          transition={{ duration: 0.2 }}
          initial={String(isOpen)}
          animate={String(isOpen)}
          height={["auto", "auto !important"]}
          opacity={["1", "1 !important"]}
        >
          {[...Array(nav.href.length).keys()].map(i => {
            return (
              <Link key={i} href={nav.href[i]} passHref>
                <Clickable ml={i === 0 ? 0 : [0, 30]} mb={[20, 0]}>
                  <Text
                    color={i === 0 ? "gold" : "black"}
                    fontSize={16}
                    fontWeight="bold"
                  >
                    {nav.title_jp[i]}
                  </Text>
                  <Text
                    pl={4}
                    color={i === 0 ? "gold" : "black"}
                    fontSize={12}
                    fontWeight="bold"
                  >
                    {nav.title_en[i]}
                  </Text>
                </Clickable>
              </Link>
            )
          })}
        </MotionDiv>
      </OutsideClickHandler>
    </Box>
  );
}


function TopBar({ top_bar }) {
  return (
    <Box
      px={["5%", 80]}
      width="100%"
      height={54}
      alignItems="center" justifyContent="center"
      display="flex"
      pt={10}
    >
      <Text
        display="flex" alignItems="center" justifyContent="center"
        color="black"
        fontSize={16}
      >
        <Image width={26} height={26} src="/img/general/logo.png" alt="logo"></Image>
        <Box
          as="span"
          color="black"
          fontSize={26}
          mr={10}
          ml={10}
          fontWeight="bold"
        >
          {top_bar.company}
        </Box>
        <Text display={["none", "block"]}>
          {top_bar.short_catchphrase_jp}
        </Text>
      </Text>
      <Text
        ml="auto"
        color="black"
        fontSize={16}
        display={["none", "none", "block"]}
      >
        {top_bar.short_catchphrase_en}
      </Text>
      <Box display="flex" ml="auto">
        <Clickable
          as="a"
          href="https://www.instagram.com/hamu_kimi5118"
          target="_blank"
          mr={[0, 20]}
        >
          <Image src="/img/svg/instagram.svg" width={18} height={18} alt="instagram"></Image>
        </Clickable>
        <Box alignItems="center" justifyContent="center" display={["none", "flex"]}>
          <Image width={18} height={18} src="/img/svg/phone.svg" alt="phone"></Image>
          <Text color="black" fontSize={16} ml={4} >
            {top_bar.phone_number}
          </Text>
        </Box>
      </Box>
    </Box>
  );
}

function Subheading({ subheading, nav }) {
  return (
    <Box
      display="flex" alignItems="flex-start" justifyContent="center" flexDirection="column"
      style={{ boxSizing: "border-box" }}
      px={["5%", "10%", "10%"]}
      width="100%"
      height={["calc(100% - 94px)", "calc(100% - 144px)"]}
    >
      <Text
        mb={30}
        color="black"
        fontSize={[24, 28]}
      >
        {subheading.subtitle}
      </Text>
      <Text
        mb={30}
        color="black"
        fontSize={[54, 64, 64]}
        lineHeight="1.05"
        fontWeight="bold"
      >
        {
          subheading.title.split('<br>').map((str, index) => {
            return (
              <React.Fragment key={index}>{str}<br /></React.Fragment>
            )
          })
        }
      </Text>
      <Text
        mb={30}
        maxWidth={500}
        color="grey5"
        fontSize={14}
        lineHeight="2.07"
        fontWeight="bold"
        style={{ textShadow: "0 0 2px  rgba(255, 255, 255, 1" }}
      >
        {subheading.body}
      </Text>
      <Button height={50} href={nav.href[1]}>
        撮影を予約する
      </Button>
    </Box>
  )
}
